/*
the following tool had a ton of trouble getting ambient light to work, specifically the darker
textures and things like that. Eventurally it was easier to just not.
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'


export default function FolioModel(props) {


    const gltf = useLoader(GLTFLoader, "./models/intro/static/base.glb")

    //rotation should match with introsection.js's static placement to line up with collision
    //also holds all of the other objects on the desk
    // may add annother for below.
    return <primitive object={gltf.scene} scale={[4,4,4]} rotation={[0,0,.4]} offset={[0,0,0]}/>
}

useGLTF.preload("./models/intro/static/base.glb");


