/*
the following tool had a ton of trouble getting ambient light to work, specifically the darker
textures and things like that. Eventurally it was easier to just not.
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'


export default function FolioModel(props) {

    const gltf = useLoader(GLTFLoader, "./models/intro/static/base.glb")
    return <primitive object={gltf.scene} scale={[9,9,9]} rotation={[0,0,3]} />
}

useGLTF.preload("./models/intro/static/base.glb");
